### PR TITLE
Add "Dependency specification and update policies" and update for poetry and dependabot

### PR DESCRIPTION
**Pull request by legoktm**
## Status

Ready for review 

## Description of Changes

The first commit is a copy of the [wiki page](https://github.com/freedomofpress/securedrop/wiki/Dependency-specification-and-update-policies) with the syntax translated from markdown to RST, no other changes.

The second commit is the main changes, adding in references to poetry/pyproject.toml, an dependabot. In summary:

* Introduce that we use pip-compile but are migrating to poetry.
* Update examples to mention `pyproject.toml` and poetry's caret
  operator.
* Explain dependabot and document that reviewers must manually verify
the checksums provided by GitHub.
* Update section on reproducible wheels.

## Testing

* Visual review

## Release 

* Just need to update the wiki page to point to the published documentation when it's deployed.

## Checklist (Optional)

- [x] Doc linting (`make docs-lint`) passed locally
- [ ] Doc link linting (`make docs-linkcheck`) passed
- [x] You have previewed (`make docs`) docs at http://localhost:8000

### CODE REVIEW

**Comment by eloquence** [comment]
@legoktm Added some docs for getting to the hashes on PyPI since that was not immediately obvious to me, let me know if that looks good to you or if there's an easier path, happy to tweak :)

**Comment by legoktm** [comment]
That's exactly what I was doing too, lgtm!

**Review by eloquence — APPROVED** [review]
LGTM. As you say, content is mostly identical to the wiki page; Dependabot/Poetry-specific updates seem minimal and straighforward, but letting it sit for a few days in case Kev or others want to weigh in :)

**Review by cfm — CHANGES_REQUESTED** [review]
This looks great to me, @legoktm.  I tripped over one typo, for which I've suggested a correction.

Is it your expectation that we'll redirect <https://github.com/freedomofpress/securedrop/wiki/Dependency-specification-and-update-policies> to this documentation page?

**Comment by legoktm** [comment]
Thanks, pushed the typo fix.

> Is it your expectation that we'll redirect https://github.com/freedomofpress/securedrop/wiki/Dependency-specification-and-update-policies to this documentation page?

Yes. I don't think a proper redirect is technically possible, but something like "This page has moved to X".

**Comment by eloquence** [comment]
Thank you both, I've updated the wiki page to point to the docs :)

**Pull request merged**
